package app

import (
	"bytes"
	_ "embed"
	"fmt"
	"net/http"
	"strconv"
	"strings"

	"codeberg.org/go-pdf/fpdf"
	"github.com/martin3zra/forge/foundation"
	"github.com/martin3zra/acme/pkg/i18n"
)

//go:embed assets/logo.b64
var logoBase64 []byte

type InvoicePDF struct {
	pdf     *fpdf.Fpdf
	trans   *i18n.Translator
	invoice *invoice
	lines   []*line
	logo    []byte
}

func NewInvoicePDF(trans *i18n.Translator, i *invoice, lines []*line) (*InvoicePDF, error) {

	logo, err := decodeLogo()
	if err != nil {
		return nil, err
	}
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 20, 15)
	pdf.SetAutoPageBreak(true, 25)
	pdf.AddPage()
	// Enables total page count
	pdf.AliasNbPages("")

	if err := registerFonts(pdf); err != nil {
		return nil, err
	}

	pdf.SetFont("DejaVu", "", 11)
	return &InvoicePDF{pdf: pdf, trans: trans, invoice: i, lines: lines, logo: logo}, pdf.Error()
}

func (i *InvoicePDF) t(key string, replacements ...i18n.Replacements) string {
	return i.trans.Trans(key, replacements...)
}

func (i *InvoicePDF) AddLogo() {
	i.pdf.RegisterImageOptionsReader("logo", fpdf.ImageOptions{
		ImageType: "PNG",
	}, bytes.NewReader(i.logo))
	i.pdf.ImageOptions("logo", 15, 10, 30, 0, false, fpdf.ImageOptions{
		ImageType: "PNG",
	}, 0, "")
}

func (i *InvoicePDF) Header(company *Company) {
	i.AddLogo()

	// Company Info (top left)
	i.pdf.SetFont("DejaVu", "", 10)
	i.pdf.SetXY(50, 10)
	i.pdf.MultiCell(80, 5, fmt.Sprintf("%s\n%s\n%s", company.Name, company.Address+"\n"+company.City, ""), "", "", false)
	i.pdf.SetXY(50, 25)
	i.pdf.CellFormat(80, 6, fmt.Sprintf("%s: %s", i.t("companies.single.rnc_short"), company.Identifier), "", 1, "", false, 0, "")

	// Invoice Info (top right)
	i.pdf.SetXY(150, 10)
	i.pdf.CellFormat(0, 6, fmt.Sprintf("%s: %s", i.t(fmt.Sprintf("global.%s", i.invoice.Kind)), i.invoice.Number), "", 1, "R", false, 0, "")
	if i.invoice.Kind == TransactionKinds.Invoice {
		i.pdf.CellFormat(0, 6, fmt.Sprintf("NCF: %s", *i.invoice.NCF), "", 1, "R", false, 0, "")
	}
	i.pdf.CellFormat(0, 6, fmt.Sprintf("%s: %s", i.t("global.date"), i.invoice.Date.Format("2006-01-02")), "", 1, "R", false, 0, "")
	if i.invoice.Kind != TransactionKinds.Invoice {
		i.pdf.Ln(6)
	}
	i.pdf.Ln(10)
	i.pdf.Line(15, i.pdf.GetY(), 195, i.pdf.GetY())
	i.pdf.Ln(10)

	// BILL TO & PAYMENT
	i.pdf.SetFont("DejaVu", "B", 10)
	i.pdf.CellFormat(90, 6, strings.ToUpper(i.t(fmt.Sprintf("global.%sTo", i.invoice.Kind))), "", 0, "", false, 0, "")
	if i.invoice.Kind == TransactionKinds.Invoice {
		i.pdf.CellFormat(90, 6, strings.ToUpper(i.t("global.paymentTerms")), "", 1, "", false, 0, "")
	} else {
		i.pdf.Ln(6)
	}
	i.pdf.SetFont("DejaVu", "", 10)

	i.pdf.CellFormat(90, 6, i.invoice.Customer.Name, "", 0, "", false, 0, "")
	if i.invoice.DueOn != nil {
		i.pdf.CellFormat(90, 6, fmt.Sprintf("%s %s", i.t("global.dueDate"), i.invoice.DueOn.Format("2006-01-02")), "", 1, "", false, 0, "")
	} else {
		if i.invoice.Kind == TransactionKinds.Invoice {
			i.pdf.CellFormat(90, 6, strings.ToUpper(i.invoice.Terms), "", 1, "", false, 0, "")
		} else {
			i.pdf.Ln(6)
		}
	}
	i.pdf.CellFormat(90, 6, fmt.Sprintf("%s: %s", i.t("global.email"), i.invoice.Customer.Email), "", 0, "", false, 0, "")
	if i.invoice.DueOn != nil {
		i.pdf.CellFormat(90, 6, fmt.Sprintf("%s: %s", i.t("global.balance"), foundation.FormatAmount(i.invoice.AmountDue)), "", 1, "", false, 0, "")
	} else {
		i.pdf.Ln(6)
	}
	i.pdf.CellFormat(90, 6, fmt.Sprintf("%s: %s", i.t("global.phone"), i.invoice.Customer.Phone), "", 0, "", false, 0, "")
	i.pdf.Ln(12)

}

func (i *InvoicePDF) Footer(text string) {
	i.pdf.SetFooterFunc(func() {
		i.pdf.SetY(-15)
		i.pdf.SetFont("DejaVu", "I", 8)
		i.pdf.SetTextColor(0, 0, 0)
		footer := fmt.Sprintf("Page %d/{nb}", i.pdf.PageNo())
		i.pdf.CellFormat(
			10, 10, fmt.Sprintf("Generated by %s v0", text), "", 0, "L", false, 0, "",
		)
		i.pdf.CellFormat(
			0, 10, footer, "", 0, "C", false, 0, "",
		)
	})
}

func (i *InvoicePDF) Lines() {
	// Table Header
	i.pdf.SetFont("DejaVu", "B", 10)
	i.pdf.SetFillColor(240, 240, 255)
	headers := []string{i.t("global.reference"), i.t("global.item"), i.t("global.unit"), i.t("global.qtyAbrev"), i.t("global.price"), i.t("global.tax"), i.t("global.amount")}
	aligns := []string{"", "", "C", "C", "R", "R", "R"}
	widths := []float64{33, 45, 15, 15, 25, 22, 25}

	for idx, h := range headers {
		i.pdf.CellFormat(widths[idx], 8, h, "1", 0, aligns[idx], true, 0, "")
	}
	i.pdf.Ln(-1)

	// Table Body
	i.pdf.SetFont("DejaVu", "", 9)
	var subtotal, totalTax float64
	for _, line := range i.lines {
		lineTotal := float64(line.Qty)*line.Price + line.Tax.Amount
		subtotal += float64(line.Qty) * line.Price
		totalTax += line.Tax.Amount

		reference := ""
		if line.Identifier.Reference != nil {
			reference = *line.Identifier.Reference
		}

		i.pdf.CellFormat(widths[0], 8, reference, "1", 0, "", false, 0, "")
		i.pdf.CellFormat(widths[1], 8, truncate(i.pdf, line.Name, widths[1]-3), "1", 0, "", false, 0, "")
		i.pdf.CellFormat(widths[2], 8, line.Unit.Name, "1", 0, "C", false, 0, "")
		i.pdf.CellFormat(widths[3], 8, strconv.FormatInt(line.Qty, 10), "1", 0, "C", false, 0, "")
		i.pdf.CellFormat(widths[4], 8, foundation.FormatAmount(line.Price), "1", 0, "R", false, 0, "")
		i.pdf.CellFormat(widths[5], 8, foundation.FormatAmount(line.Tax.Amount), "1", 0, "R", false, 0, "")
		i.pdf.CellFormat(widths[6], 8, foundation.FormatAmount(lineTotal), "1", 1, "R", false, 0, "")
	}

	i.pdf.Ln(10)

	i.Totals(subtotal, totalTax)
	if i.invoice.Kind == TransactionKinds.Invoice {
		i.watermark()
	}
}

func (i *InvoicePDF) Totals(subtotal, totalTax float64) {

	i.pdf.SetFont("DejaVu", "B", 10)
	// Totals (Right-aligned)
	rightX := 195.0
	labelW := 30.0
	valW := 30.0
	offset := labelW + valW

	// Draw horizontal line
	y := i.pdf.GetY()
	i.pdf.Line(15, y, 195, y)
	i.pdf.Ln(2)

	if strings.TrimSpace(i.invoice.Notes) != "" {
		i.pdf.CellFormat(labelW, 8, i.t("global.notes"), "", 0, "L", false, 0, "")
		i.pdf.Ln(6)
		i.pdf.SetFont("DejaVu", "", 10)
		i.pdf.CellFormat(100, 8, i.invoice.Notes, "", 0, "L", false, 0, "")
	}

	i.pdf.SetY(y + 3)
	i.pdf.SetX(rightX - offset)
	i.pdf.CellFormat(labelW, 6, i.t("global.subTotal"), "", 0, "R", false, 0, "")
	i.pdf.CellFormat(valW, 6, foundation.FormatAmount(subtotal), "", 1, "R", false, 0, "")

	discountAmount := i.invoice.Discount.Val
	discountPercentage := i.invoice.Discount.Val
	if i.invoice.Discount.Type == "percentage" {
		discountAmount = float64(i.invoice.Amount * (discountPercentage / 100))
	}
	if discountPercentage > 0 {
		i.pdf.CellFormat(130, 6, foundation.FormatAmount(discountPercentage, "%"), "", 0, "R", false, 0, "")
	}
	i.pdf.SetX(rightX - offset)
	i.pdf.CellFormat(labelW, 6, i.t("global.discount"), "", 0, "R", false, 0, "")
	i.pdf.CellFormat(valW, 6, foundation.FormatAmount(discountAmount), "", 1, "R", false, 0, "")
	i.pdf.SetX(rightX - offset)
	i.pdf.CellFormat(labelW, 6, i.t("global.tax"), "", 0, "R", false, 0, "")
	i.pdf.CellFormat(valW, 6, foundation.FormatAmount(totalTax), "", 1, "R", false, 0, "")
	i.pdf.SetFont("DejaVu", "B", 10)
	i.pdf.SetX(rightX - offset)
	i.pdf.SetFillColor(220, 240, 255) // light blue
	i.pdf.CellFormat(labelW, 8, i.t("global.total"), "", 0, "R", false, 0, "")
	i.pdf.CellFormat(valW, 8, foundation.FormatAmount(subtotal+totalTax), "", 1, "R", false, 0, "")

}

func (i *InvoicePDF) watermark() {
	watermarkColor := struct {
		Red   int
		Green int
		Blue  int
	}{150, 0, 0}

	watermarkText := ""
	if i.invoice.Status == InvoiceStatuses.Void {
		watermarkText = string(i.invoice.Status)
	}

	if i.invoice.PaidStatus == PaidStatuses.Paid {
		watermarkText = string(i.invoice.PaidStatus)
		watermarkColor.Red = 0
		watermarkColor.Green = 128
	}

	if watermarkText != "" {
		opts := WatermarkOpt{
			FontFamily: "Helvetica",
			FontStyle:  "B",
			FontSize:   72,
			AngleDeg:   45,
			Opacity:    0.5,
			Spacing:    -1.0,
			Color:      watermarkColor,
		}
		drawTextWatermarkKerned(
			i.pdf,
			strings.ToUpper(watermarkText), // txt
			opts,
		)
	}
}

func (i *InvoicePDF) Output(r http.ResponseWriter) error {
	return i.pdf.Output(r)
}
