package app

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"strings"

	"codeberg.org/go-pdf/fpdf"
	"github.com/martin3zra/forge/foundation"
	"github.com/martin3zra/acme/pkg/i18n"
)

type PaymentPDF struct {
	pdf     *fpdf.Fpdf
	trans   *i18n.Translator
	payment *payment
	lines   []*paymentLine
	logo    []byte
}

func NewPaymentPDF(trans *i18n.Translator, p *payment, lines []*paymentLine) (*PaymentPDF, error) {

	logo, err := decodeLogo()
	if err != nil {
		return nil, err
	}
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 20, 15)
	pdf.SetAutoPageBreak(true, 25)
	pdf.AddPage()
	// Enables total page count
	pdf.AliasNbPages("")

	if err := registerFonts(pdf); err != nil {
		return nil, err
	}

	pdf.SetFont("DejaVu", "", 11)

	return &PaymentPDF{pdf: pdf, trans: trans, payment: p, lines: lines, logo: logo}, pdf.Error()
}

func (p *PaymentPDF) t(key string, replacements ...i18n.Replacements) string {
	return p.trans.Trans(key, replacements...)
}

func (p *PaymentPDF) AddLogo() {

	p.pdf.RegisterImageOptionsReader("logo", fpdf.ImageOptions{
		ImageType: "PNG",
	}, bytes.NewReader(p.logo))
	p.pdf.ImageOptions("logo", 15, 10, 30, 0, false, fpdf.ImageOptions{
		ImageType: "PNG",
	}, 0, "")
}

func (p *PaymentPDF) Header(ctx context.Context) {
	p.AddLogo()

	company := CurrentCompany(ctx)
	// Company Info (top left)
	p.pdf.SetFont("DejaVu", "", 10)
	p.pdf.SetXY(50, 10)
	p.pdf.MultiCell(80, 5, fmt.Sprintf("%s\n%s\n%s", company.Name, company.Address+"\n"+company.City, ""), "", "", false)
	p.pdf.SetXY(50, 25)
	p.pdf.CellFormat(80, 6, fmt.Sprintf("%s: %s", p.t("companies.single.rnc_short"), company.Identifier), "", 1, "", false, 0, "")

	// Payment Info (top right)
	p.pdf.SetXY(150, 10)
	p.pdf.CellFormat(0, 6, p.t("global.receiptOfPayment"), "", 1, "R", false, 0, "")
	p.pdf.CellFormat(0, 6, fmt.Sprintf("%s: %s", p.t("global.number"), p.payment.Code), "", 1, "R", false, 0, "")
	p.pdf.CellFormat(0, 6, fmt.Sprintf("%s: %s", p.t("global.date"), p.payment.Date.Format("2006-01-02")), "", 1, "R", false, 0, "")

	p.pdf.Ln(10)
	p.pdf.Line(15, p.pdf.GetY(), 195, p.pdf.GetY())
	p.pdf.Ln(10)

	// BILL TO & PAYMENT
	p.pdf.SetFont("DejaVu", "B", 10)
	p.pdf.CellFormat(90, 6, strings.ToUpper(p.t("global.weHaveReceivedFrom")), "", 0, "", false, 0, "")
	p.pdf.SetX(110)
	p.pdf.CellFormat(90, 6, fmt.Sprintf("%s: %s", strings.ToUpper(p.t("global.amount")), foundation.FormatAmount(p.payment.Amount)), "", 1, "", false, 0, "")
	currentX := p.pdf.GetX()
	currentY := p.pdf.GetY()
	p.pdf.SetXY(currentX+95, currentY)
	p.pdf.SetFont("DejaVu", "", 8)
	p.pdf.CellFormat(90, 6, foundation.MoneyToText(int64(p.payment.Amount*100), "pesos"), "", 1, "", false, 0, "")
	p.pdf.SetFont("DejaVu", "", 10)

	p.pdf.SetXY(currentX, currentY)
	p.pdf.MultiCell(80, 5, fmt.Sprintf("%s\n%s\n%s", p.payment.Customer.Name, p.payment.Customer.Address, ""), "", "", false)
	p.pdf.CellFormat(90, 6, fmt.Sprintf("%s: %s", p.t("global.email"), p.payment.Customer.Email), "", 0, "", false, 0, "")
	p.pdf.Ln(6)
	p.pdf.CellFormat(90, 6, fmt.Sprintf("%s: %s", p.t("global.phone"), p.payment.Customer.Phone), "", 0, "", false, 0, "")
	p.pdf.Ln(12)

}

func (p *PaymentPDF) Footer(text string) {
	p.pdf.SetFooterFunc(func() {
		p.pdf.SetY(-15)
		p.pdf.SetFont("DejaVu", "I", 8)
		p.pdf.SetTextColor(0, 0, 0)
		footer := fmt.Sprintf("Page %d/{nb}", p.pdf.PageNo())
		p.pdf.CellFormat(
			10, 10, fmt.Sprintf("Generated by %s v0", text), "", 0, "L", false, 0, "",
		)
		p.pdf.CellFormat(
			0, 10, footer, "", 0, "C", false, 0, "",
		)
	})

	if strings.TrimSpace(p.payment.Notes) != "" {
		p.pdf.SetY(p.pdf.GetY() + 20)
		p.pdf.SetFont("DejaVu", "B", 10)
		p.pdf.CellFormat(30, 8, p.t("global.notes"), "", 0, "L", false, 0, "")
		p.pdf.Ln(6)
		p.pdf.SetFont("DejaVu", "", 10)
		p.pdf.CellFormat(100, 8, p.payment.Notes, "", 0, "L", false, 0, "")
	}
}

func (p *PaymentPDF) Customer(name, address string) {
	p.pdf.Cell(0, 6, "Cliente:")
	p.pdf.Ln(6)

	p.pdf.SetFont("DejaVu", "B", 11)
	p.pdf.Cell(0, 6, name)
	p.pdf.Ln(6)

	p.pdf.SetFont("DejaVu", "", 11)
	p.pdf.MultiCell(0, 6, address, "", "", false)
	p.pdf.Ln(4)
}

func (p *PaymentPDF) Lines() {

	// Table Header
	p.pdf.SetFont("DejaVu", "B", 10)
	p.pdf.SetFillColor(240, 240, 255)
	headers := []string{
		p.t("global.number"),
		p.t("global.date"),
		p.t("global.amount"),
		p.t("global.payment"),
		p.t("global.dueDateAbrev"),
		p.t("global.balance"),
		p.t("global.status")}
	aligns := []string{"", "", "R", "R", "", "R", "R"}
	widths := []float64{38, 25, 25, 25, 25, 25, 18}

	for i, h := range headers {
		p.pdf.CellFormat(widths[i], 8, h, "1", 0, aligns[i], true, 0, "")
	}
	p.pdf.Ln(-1)

	// Table Body
	p.pdf.SetFont("DejaVu", "", 9)
	for _, line := range p.lines {
		p.pdf.CellFormat(widths[0], 8, line.Invoice.Code, "1", 0, "", false, 0, "")
		p.pdf.CellFormat(widths[1], 8, line.Invoice.Date.Format("2006-01-02"), "1", 0, "", false, 0, "")
		p.pdf.CellFormat(widths[4], 8, foundation.FormatAmount(line.Invoice.Amount), "1", 0, "R", false, 0, "")
		p.pdf.CellFormat(widths[5], 8, foundation.FormatAmount(line.Payment), "1", 0, "R", false, 0, "")
		p.pdf.CellFormat(widths[2], 8, line.Invoice.DueOn.Format("2006-01-02"), "1", 0, "", false, 0, "")
		p.pdf.CellFormat(widths[3], 8, foundation.FormatAmount(line.Invoice.Amount-line.Payment), "1", 0, "R", false, 0, "")
		p.pdf.CellFormat(widths[6], 8, p.t("global.paymentLinesPaidStatuses."+string(line.Invoice.PaidStatus)), "1", 1, "C", false, 0, "")
	}
}

func (p *PaymentPDF) Total(label string, amount float64) {
	p.pdf.SetFont("DejaVu", "B", 11)
	p.pdf.CellFormat(120, 8, label, "", 0, "R", false, 0, "")
	p.pdf.CellFormat(30, 8, fmt.Sprintf("%.2f", amount), "", 0, "R", false, 0, "")
	p.pdf.Ln(8)
}

func (p *PaymentPDF) Output(r http.ResponseWriter) error {
	return p.pdf.Output(r)
}
