package app

import (
	"bytes"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"time"

	"codeberg.org/go-pdf/fpdf"
	"github.com/martin3zra/acme/pkg/foundation"
	"github.com/martin3zra/acme/pkg/i18n"
)

type SalesCustomerWisePDF struct {
	pdf   *fpdf.Fpdf
	trans *i18n.Translator
	sales []*SalesByCustomer
	From  time.Time
	To    time.Time
}

func NewSalesCustomerWisePDF(trans *i18n.Translator, sales []*SalesByCustomer, from, to time.Time) (*SalesCustomerWisePDF, error) {

	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 20, 15)
	pdf.SetAutoPageBreak(true, 25)
	// Enables total page count
	pdf.AliasNbPages("")

	if err := registerFonts(pdf); err != nil {
		return nil, err
	}

	pdf.SetFont("DejaVu", "", 11)
	return &SalesCustomerWisePDF{pdf: pdf, trans: trans, sales: sales, From: from, To: to}, pdf.Error()
}

func (i *SalesCustomerWisePDF) t(key string, replacements ...i18n.Replacements) string {
	return i.trans.Trans(key, replacements...)
}

func (i *SalesCustomerWisePDF) AddLogo() {
	logoBytes, err := base64.StdEncoding.DecodeString(logoBase64)
	if err == nil {
		i.pdf.RegisterImageOptionsReader("logo", fpdf.ImageOptions{
			ImageType: "PNG",
		}, bytes.NewReader(logoBytes))
		i.pdf.ImageOptions("logo", 15, 10, 30, 0, false, fpdf.ImageOptions{
			ImageType: "PNG",
		}, 0, "")
	}
}

func (i *SalesCustomerWisePDF) Header(ctx context.Context) {
	i.pdf.SetHeaderFunc(func() {
		i.AddLogo()

		company := CurrentCompany(ctx)
		// Company Info (top left)
		i.pdf.SetFont("DejaVu", "", 10)
		i.pdf.SetXY(50, 10)
		i.pdf.MultiCell(80, 5, fmt.Sprintf("%s\n%s\n%s", company.Name, company.Address, ""), "", "", false)
		i.pdf.SetXY(50, 25)
		i.pdf.CellFormat(80, 6, fmt.Sprintf("%s: %s", i.t("companies.single.rnc_short"), company.Identifier), "", 1, "", false, 0, "")

		// Invoice Info (top right)
		i.pdf.SetXY(150, 10)
		i.pdf.CellFormat(0, 6, fmt.Sprintf("%s - %s", i.From.Format("2006-01-02"), i.To.Format("2006-01-02")), "", 1, "R", false, 0, "")

		i.pdf.Ln(12)
	})

}

func (i *SalesCustomerWisePDF) Footer(text string) {
	i.pdf.SetFooterFunc(func() {
		i.pdf.SetY(-15)
		i.pdf.SetFont("DejaVu", "I", 8)
		i.pdf.SetTextColor(0, 0, 0)
		footer := fmt.Sprintf("Page %d/{nb}", i.pdf.PageNo())
		i.pdf.CellFormat(
			10, 10, fmt.Sprintf("Generated by %s v0", text), "", 0, "L", false, 0, "",
		)
		i.pdf.CellFormat(
			0, 10, footer, "", 0, "C", false, 0, "",
		)
	})

}

func (i *SalesCustomerWisePDF) Lines() {

	i.pdf.Ln(10)
	// Table Header
	i.pdf.SetFont("DejaVu", "B", 10)
	i.pdf.SetFillColor(240, 240, 255)
	widths := []float64{155, 25}
	// Table Body
	i.pdf.SetFont("DejaVu", "", 10)
	for _, line := range i.sales {
		i.pdf.CellFormat(widths[0], 8, line.CustomerName, "0", 0, "", false, 0, "")
		i.pdf.CellFormat(widths[1], 8, foundation.FormatAmount(line.TotalSales), "0", 0, "R", false, 0, "")
		i.pdf.Ln(-1)
	}

	i.pdf.Ln(10)
}

func (i *SalesCustomerWisePDF) Output(r http.ResponseWriter) error {
	return i.pdf.Output(r)
}

type SalesCustomerWiseWithInvoicesPDF struct {
	pdf          *fpdf.Fpdf
	trans        *i18n.Translator
	sales        []*SalesByCustomerWithInvoices
	From         time.Time
	To           time.Time
	bottomMargin float64
}

func NewSalesCustomerWiseWithInvoicesPDF(trans *i18n.Translator, sales []*SalesByCustomerWithInvoices, from, to time.Time) (*SalesCustomerWiseWithInvoicesPDF, error) {

	buttomMargin := 25.0
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 20, 15)
	pdf.SetAutoPageBreak(true, buttomMargin)

	pdf.AliasNbPages("")

	if err := registerFonts(pdf); err != nil {
		return nil, err
	}

	pdf.SetFont("DejaVu", "", 11)
	return &SalesCustomerWiseWithInvoicesPDF{pdf: pdf, trans: trans, sales: sales, From: from, To: to, bottomMargin: buttomMargin}, pdf.Error()
}

func (i *SalesCustomerWiseWithInvoicesPDF) t(key string, replacements ...i18n.Replacements) string {
	return i.trans.Trans(key, replacements...)
}

func (i *SalesCustomerWiseWithInvoicesPDF) AddLogo() {
	logoBytes, err := base64.StdEncoding.DecodeString(logoBase64)
	if err == nil {
		i.pdf.RegisterImageOptionsReader("logo", fpdf.ImageOptions{
			ImageType: "PNG",
		}, bytes.NewReader(logoBytes))
		i.pdf.ImageOptions("logo", 15, 10, 30, 0, false, fpdf.ImageOptions{
			ImageType: "PNG",
		}, 0, "")
	}
}

func (i *SalesCustomerWiseWithInvoicesPDF) Header(ctx context.Context) {
	i.pdf.SetHeaderFunc(func() {
		i.AddLogo()

		company := CurrentCompany(ctx)
		// Company Info (top left)
		i.pdf.SetFont("DejaVu", "", 10)
		i.pdf.SetXY(50, 10)
		i.pdf.MultiCell(80, 5, fmt.Sprintf("%s\n%s\n%s", company.Name, company.Address, ""), "", "", false)
		i.pdf.SetXY(50, 25)
		i.pdf.CellFormat(80, 6, fmt.Sprintf("%s: %s", i.t("companies.single.rnc_short"), company.Identifier), "", 1, "", false, 0, "")

		// Invoice Info (top right)
		i.pdf.SetXY(150, 10)
		i.pdf.CellFormat(0, 6, fmt.Sprintf("%s - %s", i.From.Format("2006-01-02"), i.To.Format("2006-01-02")), "", 1, "R", false, 0, "")

		i.pdf.Ln(22)
	})
}

func (i *SalesCustomerWiseWithInvoicesPDF) Footer(text string) {
	i.pdf.SetFooterFunc(func() {
		i.pdf.SetY(-15)
		i.pdf.SetFont("DejaVu", "I", 8)
		i.pdf.SetTextColor(0, 0, 0)
		footer := fmt.Sprintf("Page %d/{nb}", i.pdf.PageNo())
		i.pdf.CellFormat(
			10, 10, fmt.Sprintf("Generated by %s v0", text), "", 0, "L", false, 0, "",
		)
		i.pdf.CellFormat(
			0, 10, footer, "", 0, "C", false, 0, "",
		)
	})

}

func (i *SalesCustomerWiseWithInvoicesPDF) Lines(groups []CustomerGroup) {
	if i.pdf.PageNo() == 0 {
		i.pdf.AddPage()
	}

	i.pdf.SetFont("DejaVu", "B", 14)
	i.pdf.CellFormat(0, 10, "Sales Report: By Customer", "", 1, "", false, 0, "")

	var grandTotal float64
	for _, group := range groups {
		// Estimate row height: header + at least one invoice line
		headerHeight := 10.0
		invoiceRowHeight := 8.0

		// Check if there's room for header + at least one invoice row
		if i.NeedsNewPage(headerHeight + invoiceRowHeight) {
			i.pdf.AddPage()
		}

		// Print customer header
		i.pdf.SetFont("DejaVu", "B", 12)
		i.pdf.CellFormat(0, headerHeight, group.CustomerName, "", 1, "", false, 0, "")

		// Print invoices
		i.pdf.SetFont("DejaVu", "", 10)
		var subtotal float64
		for _, inv := range group.Invoices {
			date := inv.Date.Format("02 Jan 2006")
			left := fmt.Sprintf("%s (INV-%06d)", date, inv.InvoiceID)
			right := foundation.FormatAmount(inv.Total)

			if i.NeedsNewPage(invoiceRowHeight) {
				i.pdf.AddPage()
			}

			i.pdf.CellFormat(155, invoiceRowHeight, left, "", 0, "", false, 0, "")
			i.pdf.CellFormat(25, invoiceRowHeight, right, "", 1, "R", false, 0, "")
			subtotal += inv.Total
		}

		// Subtotal + total lines
		lineY := i.pdf.GetY()       // current vertical position
		leftMargin := 15.0          // match your SetMargins
		rightMargin := 210.0 - 15.0 // A4 width (210mm) minus right margin

		// Draw a light gray line across the page
		i.pdf.SetDrawColor(200, 200, 200) // light gray
		i.pdf.Line(leftMargin, lineY, rightMargin, lineY)

		i.pdf.SetFont("DejaVu", "B", 10)

		// Subtotal + total lines
		i.pdf.CellFormat(155, invoiceRowHeight, "", "", 0, "", false, 0, "")
		i.pdf.CellFormat(25, invoiceRowHeight, foundation.FormatAmount(subtotal), "", 1, "R", false, 0, "")
	}
	i.pdf.SetFont("DejaVu", "B", 10)
	i.pdf.CellFormat(155, 10, "TOTAL SALES", "", 0, "", false, 0, "")
	i.pdf.CellFormat(25, 10, foundation.FormatAmount(grandTotal), "", 1, "R", false, 0, "")

	i.pdf.Ln(5)
}

// UsableHeight returns the vertical space available on the current page
// after accounting for the bottom margin.
func (i *SalesCustomerWiseWithInvoicesPDF) UsableHeight() float64 {
	_, pageHeight := i.pdf.GetPageSize()
	return pageHeight - i.bottomMargin
}

// NeedsNewPage checks if the required height fits in the remaining space.
// If not, you should call AddPage() before printing.
func (i *SalesCustomerWiseWithInvoicesPDF) NeedsNewPage(requiredHeight float64) bool {
	y := i.pdf.GetY()
	return y+requiredHeight > i.UsableHeight()
}

func (i *SalesCustomerWiseWithInvoicesPDF) Output(r http.ResponseWriter) error {
	return i.pdf.Output(r)
}

type SalesReportPDF struct {
	pdf          *fpdf.Fpdf
	trans        *i18n.Translator
	sales        []*SalesByCustomerWithInvoices
	From, To     time.Time
	bottomMargin float64
	showInvoices bool
}

func NewSalesReportPDF(trans *i18n.Translator, from, to time.Time, showInvoices bool) (*SalesReportPDF, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 20, 15)
	pdf.SetAutoPageBreak(true, 25)
	pdf.AliasNbPages("")

	if err := registerFonts(pdf); err != nil {
		return nil, err
	}

	pdf.SetFont("DejaVu", "", 11)

	return &SalesReportPDF{
		pdf:          pdf,
		trans:        trans,
		From:         from,
		To:           to,
		bottomMargin: 25,
		showInvoices: showInvoices,
	}, pdf.Error()
}

func (r *SalesReportPDF) Render(groups []CustomerGroup) {
	if r.pdf.PageNo() == 0 {
		r.pdf.AddPage()
	}

	r.pdf.SetFont("DejaVu", "B", 14)
	r.pdf.CellFormat(0, 10, "Sales Report: By Customer", "", 1, "", false, 0, "")

	var grandTotal float64
	for idx, group := range groups {
		headerHeight := 10.0
		invoiceRowHeight := 8.0

		if r.NeedsNewPage(headerHeight + invoiceRowHeight) {
			r.pdf.AddPage()
		}

		if r.showInvoices {
			// Customer header
			r.pdf.SetFont("DejaVu", "B", 12)
			r.pdf.CellFormat(0, headerHeight, group.CustomerName, "", 1, "", false, 0, "")

			// Invoices
			r.pdf.SetFont("DejaVu", "", 10)
			var subtotal float64
			for _, inv := range group.Invoices {
				if r.NeedsNewPage(invoiceRowHeight) {
					r.pdf.AddPage()
				}
				date := inv.Date.Format("02 Jan 2006")
				left := fmt.Sprintf("%s (INV-%06d)", date, inv.InvoiceID)
				right := foundation.FormatAmount(inv.Total)

				r.pdf.CellFormat(155, invoiceRowHeight, left, "", 0, "", false, 0, "")
				r.pdf.CellFormat(25, invoiceRowHeight, right, "", 1, "R", false, 0, "")
				subtotal += inv.Total
			}

			// 🔑 set group.Total so grand total works
			group.Total = subtotal

			// Separator line above subtotal
			lineY := r.pdf.GetY()
			r.pdf.SetDrawColor(200, 200, 200)
			r.pdf.Line(15, lineY, 195, lineY)

			// Subtotal line
			r.pdf.SetFont("DejaVu", "B", 10)
			r.pdf.CellFormat(155, invoiceRowHeight, "TOTAL SALES", "", 0, "", false, 0, "")
			r.pdf.CellFormat(25, invoiceRowHeight, foundation.FormatAmount(group.Total), "", 1, "R", false, 0, "")
			r.pdf.Ln(5)

		} else {
			rowHeight := 8.0
			// Summary mode: name + total on same line
			r.pdf.SetFont("DejaVu", "", 11)
			r.pdf.CellFormat(155, rowHeight, group.CustomerName, "", 0, "", false, 0, "")
			r.pdf.CellFormat(25, rowHeight, foundation.FormatAmount(group.Total), "", 1, "R", false, 0, "")

			// If this is the last customer, draw separator line
			if idx == len(groups)-1 {
				lineY := r.pdf.GetY() + 2 // a little below last line
				r.pdf.SetDrawColor(200, 200, 200)
				r.pdf.Line(15, lineY, 195, lineY)
			}
		}

		grandTotal += group.Total
	}

	r.pdf.Ln(2)
	r.pdf.SetFont("DejaVu", "B", 12)
	r.pdf.CellFormat(155, 10, "GRAND TOTAL", "", 0, "", false, 0, "")
	r.pdf.CellFormat(25, 10, foundation.FormatAmount(grandTotal), "", 1, "R", false, 0, "")
}

// NeedsNewPage checks if the required height fits in the remaining space.
// If not, you should call AddPage() before printing.
func (i *SalesReportPDF) NeedsNewPage(requiredHeight float64) bool {
	y := i.pdf.GetY()
	return y+requiredHeight > i.UsableHeight()
}

// UsableHeight returns the vertical space available on the current page
// after accounting for the bottom margin.
func (i *SalesReportPDF) UsableHeight() float64 {
	_, pageHeight := i.pdf.GetPageSize()
	return pageHeight - i.bottomMargin
}
